### ISSUE TITLE
'AppCenter/AppCenter.h' file not found

### ISSUE THREAD

**Issue by FabianVarela** [aloisdeniel/flutter_plugin_appcenter#14]
Hi there.

Actually I'm have an error to run the application with iOS. I'm using the simulator to run the app.

```shell
/Users/macbook/flutter/.pub-cache/hosted/pub.dartlang.org/appcenter-0.2.1/ios/Classes/AppcenterPlugin.m:3:9: fatal error: 'AppCenter/AppCenter.h' file not found
    #import <AppCenter/AppCenter.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.
```

This is my flutter doctor

```shell
flutter doctor -v

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale es-CO)
    • Flutter version 1.7.8+hotfix.4 at /Users/macbook/flutter
    • Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • TA 1025   • PLEGAR27B1010086                     
    • android-arm64 • Android 9 (API 28)
    • iPhone Xʀ • 847FE23E-FADD-4BAB-9180-79830B379D4E • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

Thanks

**Comment by tomalabaster** [comment]
How strange. Did pod install definitely run? What's the minimum iOS version
you're targeting?

**Comment by FabianVarela** [comment]
The pod installed the package successfully, but at the moment to run the app in the simulator with iOS 12, generate the error "File not found".

Even, I tried to build from XCode and the error is the same.

![Captura de Pantalla 2019-09-09 a la(s) 4 36 10 p  m](https://user-images.githubusercontent.com/8941029/64568392-3b5ee600-d320-11e9-91c4-dce4a494a452.png)

**Comment by tomalabaster** [comment]
Was the project created with Objective-C or Swift? And are there any
specific characters in the path to your project? I see you've put a line
though your path info which is fine but that warning suggests something
might not be right with the path to your project.

**Comment by FabianVarela** [comment]
Hi @tomalabaster . I checked the project path and it hasn't special characters or something like that. The project name is "test_flutter". However I found an issue about warning, and I can resolve with this Stackoverflow URL:

https://stackoverflow.com/questions/49181333/non-portable-path-to-file-yoga-prefix-pch-specified-path-differs-in-case-corru

And I change the "appcenter" folder by "AppCenter". And the warning has been fixed.

But, the error persist

Thanks

**Comment by FabianVarela** [comment]
Hi there.

I was trying to use the library again, because the XCode and the iOS have been updated, but the error persist too.

Thanks.

**Comment by tmorone-rezi** [comment]
I am also having the path problem - iOS will not compile. There is a pull request that maybe fixes this? https://github.com/aloisdeniel/flutter_plugin_appcenter/pull/16
Can we get this fix?

**Comment by FabianVarela** [comment]
@aloisdeniel or @tomalabaster, can you verify and approve extraction request #16 to see if this problem can be closed? 

Thank you so much

**Comment by tomalabaster** [comment]
@FabianVarela done.

**Comment by tomalabaster** [comment]
Realised there's still issues with this.

**Comment by FabianVarela** [comment]
Hi @tomalabaster I was testing the possible solution, but the issue continue.

**Comment by tomalabaster** [comment]
@hanabi1224 is your copy working at all?

**Comment by FabianVarela** [comment]
Hi.
Any clue with this issue? I changed my project from Objective-C to Swift, but the error persists.

Thanks

**Comment by tomalabaster** [comment]
@FabianVarela can you try my branch here: https://github.com/tomalabaster/flutter_plugin_appcenter/tree/%2314_-_iOS_build_fix

I've updated some of the Podfiles.

When including the plugin in a Flutter project, the Podfile needs `use_frameworks!` commented out like so: `# use_frameworks!`

If you get an error like your comment here:

> The pod installed the package successfully, but at the moment to run the app in the simulator with iOS 12, generate the error "File not found".
> 
> Even, I tried to build from XCode and the error is the same.
> 
> ![Captura de Pantalla 2019-09-09 a la(s) 4 36 10 p m](https://user-images.githubusercontent.com/8941029/64568392-3b5ee600-d320-11e9-91c4-dce4a494a452.png)
> 
> Thanks


then delete the folder *flutter_project_root*/ios/Pods and then run `pod install` again

**Comment by FabianVarela** [comment]
Hi @tomalabaster 

I have trying to test your advice:

1. Use your branch
![Captura de Pantalla 2019-11-21 a la(s) 7 41 07 p  m](https://user-images.githubusercontent.com/8941029/69388489-fbf53400-0c96-11ea-8a8e-109987c3094e.png)

2. I can't comment ```use_framework```, because the it depends for other packages

3. Delete the ```pod``` folder and execute the command ```pod install``` and that's ok

However, the error persists:
![Captura de Pantalla 2019-11-21 a la(s) 7 40 51 p  m](https://user-images.githubusercontent.com/8941029/69388568-378ffe00-0c97-11ea-8a99-41affa9bcb73.png)

**Comment by FabianVarela** [comment]
@tomalabaster I see some curious:

When I executed ```pod install``` the ```podfile.lock```, created this:

![Captura de Pantalla 2019-11-21 a la(s) 7 51 48 p  m](https://user-images.githubusercontent.com/8941029/69389365-d0277d80-0c99-11ea-8fd5-756ade01965e.png)

I saw your ```podfile.lock``` in your ```example``` folder and the AppCenter version is different

https://github.com/tomalabaster/flutter_plugin_appcenter/blob/%2314_-_iOS_build_fix/example/ios/Podfile.lock
