### ISSUE TITLE
I want to be a mantainer

### ISSUE THREAD

**Issue by tanure** [aloisdeniel/flutter_plugin_appcenter#21]
I want to be a new maintainer. How can we do it?

**Comment by aloisdeniel** [comment]
I just added you to the collaborators of the project ! 

IMO, an ideal solution would be to create an organisation for all microsoft related products and dedicated to Flutter (Flutter Microsoft).

**Comment by myoganugraha** [comment]
hello any update from maintainer ?
because appcenter cause build failed when implement google maps, thank you
