### ISSUE TITLE
I want to become a maintainer

### ISSUE THREAD

**Issue by DevJoaoLopes** [aloisdeniel/flutter_plugin_appcenter#22]
can you add me to the list of lib maintainers?
@aloisdeniel

**Comment by DevJoaoLopes** [comment]
someone is maintaining this lib? can someone help me or answer me?

**Comment by xperiandri** [comment]
Try pinging him to his email in his GitHub profile. His email is also connected to Skype

**Comment by aloisdeniel** [comment]
Sorry for the massive delay ! Added you to the maintener's list !
