### ISSUE TITLE
 Dart SDK 2 version?

### ISSUE THREAD

**Issue by Gorniv** [aloisdeniel/flutter_plugin_appcenter#4]
The current Dart SDK version is 2.1.0-dev.3.0.flutter-760a9690c2.

Because stiver depends on appcenter >=0.0.2 which requires SDK version <2.0.0, version solving failed.
pub get failed (1)

**Comment by ApofisXII** [comment]
Same situation here :/

**Comment by TinkeringAlways** [comment]
Any update on this?
